#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Motor,  port2,           RightFront,    tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port3,           RightBack,     tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port4,           RightLift,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           LeftLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LeftFront,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port9,           LeftBack,      tmotorVex393_MC29, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

task drive()
{
	while (true)
	{
		motor[LeftFront] = vexRT[Ch3];
		motor[LeftBack]  = vexRT[Ch3];
		motor[RightFront] = vexRT[Ch2];
		motor[RightBack] = vexRT[Ch2];
	}
}

task lift()
{
	while (true)
	{
		if (vexRT (Btn6U) == 1)
		{
			motor[RightLift] = -127;
			motor[LeftLift] = -127;
		}

		else if (vexRT (Btn6D) == 1)
		{
			motor[RightLift] = 85;
			motor[LeftLift] = 85;
		}
		else if (vexRT (Btn5U) == 1)
		{
			motor[RightLift] = -50;
			motor[LeftLift] = -50;
		}

		else if (vexRT (Btn5D) == 1)
		{
			motor[RightLift] = 40;
			motor[LeftLift] = 40;
		}
		else
		{
			motor[RightLift] = 0;
			motor[LeftLift] = 0;
		}

	}
}

int auton = 0;


//ADD all autonomous choices
void displayAuton(){
	switch(auton){
	case -2:
		displayLCDCenteredString(0, "Platform");
		break;
	case -1:
		displayLCDCenteredString(0, "Hit flag");
		break;
	case 1:
		displayLCDCenteredString(0, "Hit flag and platform");
		break;
	case 2:
		displayLCDCenteredString(0, "No auton");
		break;
	default:
		displayLCDCenteredString(0, "No auton");
		break;
	}
}

//DO NOT MODIFY
task LCDControl()
{
	clearLCDLine(0);
	clearLCDLine(1);
	bool noButtonsPressed = true;
	displayAuton();
	while(true){
		if(noButtonsPressed){ // only update auton if a button is pressed AND wasn't pressed previously
			switch(nLCDButtons){
			case kButtonLeft:
				auton --;
				displayAuton();
				break;
			case kButtonCenter:
				stopTask(LCDControl);
				break;
			case kButtonRight:
				auton++;
				displayAuton();
				break;
			}
		}//if
		noButtonsPressed = !nLCDButtons; //update if there is a button currently pressed
		wait1Msec(20);
	}//while
}//task

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	bStopTasksBetweenModes = true;
	bDisplayCompetitionStatusOnLcd = false;
	startTask(LCDControl);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	switch(auton){
	case 2:
		{
		}
		break;
	case 1:
		{
		}
		break;
	case -1:
		{
			motor[LeftFront] = 127;
			motor[LeftBack] = 127;
			motor[RightFront] = 127;
			motor[RightBack] = 127;
			wait1Msec(2000);
			motor[LeftFront] = -127;
			motor[LeftBack] = -127;
			motor[RightFront] = -127;
			motor[RightBack] = -127;
			wait1Msec(1000);
			motor[LeftFront] = 0;
			motor[LeftBack] = 0;
			motor[RightFront] = 0;
			motor[RightBack] = 0;
			wait1Msec(1200);
		}
		break;
	case -2:
		{
			motor[LeftFront] = 127;
			motor[LeftBack] = 127;
			motor[RightFront] = 127;
			motor[RightBack] = 127;
			wait1Msec(2100);
			motor[LeftFront] = 127;
			motor[LeftBack] = 127;
			motor[RightFront] = -127;
			motor[RightBack] = -127;
			wait1Msec(400);
					motor[LeftFront] = 127;
			motor[LeftBack] = 127;
			motor[RightFront] = 127;
			motor[RightBack] = 127;
			wait1Msec(500);
			motor[LeftFront] = -127;
			motor[LeftBack] = -127;
			motor[RightFront] = -127;
			motor[RightBack] = -127;
			wait1Msec(2500);
					motor[LeftFront] = 0;
			motor[LeftBack] = 0;
			motor[RightFront] = 0;
			motor[RightBack] = 0;
			wait1Msec(10000);
		}
		break;
	default:
		{

		}
	}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop
	startTask(lift);
	startTask(drive); //Starting Tasks
	while(true)
	{
		wait1Msec(1000); //Keeps the program alive
	}
}
