#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port3,           lift,          tmotorVex393_MC29, openLoop, reversed, driveRight, encoderPort, None)
#pragma config(Motor,  port4,           backLeft,      tmotorVex393_MC29, openLoop, driveLeft, encoderPort, None)
#pragma config(Motor,  port5,           frontLeft,     tmotorVex393_MC29, openLoop, driveLeft, encoderPort, None)
#pragma config(Motor,  port6,           arm,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           pusher,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           backRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"




/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

/*
int auton = 0;
int leftButton = 1;
int centerButton = 2;
int rightButton = 4;
*/


void pre_auton()
{

	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;
	/*


	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...

	clearLCDLine(0);
	clearLCDLine(1);
	displayLCDCenteredString(0, "<   Select   >");

	//select autonomous code

	int selecting = 0;
	while (selecting == 0) {

	switch(auton) {
	case 0:
	displayLCDCenteredString(0, "No Autonomous");
	if(nLCDButtons == leftButton){
	auton = 2; //goes to the previous option
	}
	else if(nLCDButtons == rightButton){
	auton ++; //goes to the next
	}
	else if(nLCDButtons == centerButton){
	auton = 0;
	displayLCDCenteredString(0, "Selected");
	selecting = 1; //breaks while loop

	}
	break;

	case 1:
	displayLCDCenteredString(0, "Short Side");
	if(nLCDButtons == leftButton){
	auton = 0; //goes to the previous option
	}
	else if(nLCDButtons == rightButton){
	auton ++; //goes to the next
	}
	else if(nLCDButtons == centerButton){
	auton = 1;
	displayLCDCenteredString(0, "Selected");
	selecting = 1; //breaks while loop

	}
	break;
	case 2:
	displayLCDCenteredString(0, "Long Side");
	if(nLCDButtons == leftButton){
	auton = 1; //goes to the previous option
	}
	else if(nLCDButtons == rightButton){
	auton ++; //goes to the next
	}
	else if(nLCDButtons == centerButton){
	auton = 2;
	displayLCDCenteredString(0, "Selected");
	selecting = 1; //breaks while loop

	}
	break;


	}
	}
	*/
}


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	writeDebugStreamLine("Here");

	/*
	if(auton == 0) { //Do Nothing
	wait1Msec(15000);
	}
	else if(auton == 1) {
	motor[frontRight] = 110; // drive for 3.6 seconds
	motor[frontLeft] = 110;
	motor[backRight] = 110;
	motor[backLeft] = 110;
	wait1Msec(4000);
	motor[frontRight] = 0; // stop for 0.5 seconds
	motor[frontLeft] = 0;
	motor[backRight] = 0;
	motor[backLeft] = 0;
	motor[arm] = 127;
	wait1Msec(500);
	motor[lift] = 100; // lift for 1 seconds
	motor[arm] = 15;
	wait1Msec(2000);
	motor[lift] = 0; // back up for 1.6 seconds
	motor[backRight] = -110;
	motor[backLeft] = -110;
	motor[frontLeft] = -110;
	motor[frontRight] = -110;
	motor[arm] = 15;
	wait1Msec(4000);
	motor[frontRight] = -110; // turn for 1.5 seconds
	motor[frontLeft] = 110;
	motor[backRight] = -110;
	motor[backLeft] = 110;
	motor[arm] = 15;
	wait1Msec(1500);
	motor[lift] = -100; // lower lift for 1 second
	motor[arm] = 15;
	wait1Msec(1000);
	motor[frontRight] = 110;
	motor[frontLeft] = 110;
	motor[backRight] = 110;
	motor[backLeft] = 110;
	motor[arm] = 15;
	wait1Msec(500);
	motor[frontRight] = -100; // back up for 1 second
	motor[frontLeft] = -100;
	motor[backRight] = -100;
	motor[backLeft] = -100;
	motor[lift] = 100;
	motor[arm] = 15;
	wait1Msec(1000);
	}
	else if(auton == 2) {
	motor[frontRight] = 110; // drive for 3.6 seconds
	motor[frontLeft] = 110;
	motor[backRight] = 110;
	motor[backLeft] = 110;
	wait1Msec(4000);
	motor[frontRight] = 0; // stop for 0.5 seconds
	motor[frontLeft] = 0;
	motor[backRight] = 0;
	motor[backLeft] = 0;
	motor[arm] = 127;
	wait1Msec(500);
	motor[lift] = 100; // lift for 1 seconds
	motor[arm] = 15;
	wait1Msec(2000);
	motor[lift] = 0; // back up for 1.6 seconds
	motor[backRight] = -110;
	motor[backLeft] = -110;
	motor[frontLeft] = -110;
	motor[frontRight] = -110;
	motor[arm] = 15;
	wait1Msec(4000);
	motor[frontRight] = -110; // turn for 1.5 seconds
	motor[frontLeft] = 110;
	motor[backRight] = -110;
	motor[backLeft] = 110;
	motor[arm] = 15;
	wait1Msec(1500);
	motor[lift] = -100; // lower lift for 1 second
	motor[arm] = 15;
	wait1Msec(1000);
	motor[frontRight] = 110;
	motor[frontLeft] = 110;
	motor[backRight] = 110;
	motor[backLeft] = 110;
	motor[arm] = 15;
	wait1Msec(500);
	motor[frontRight] = -100; // back up for 1 second
	motor[frontLeft] = -100;
	motor[backRight] = -100;
	motor[backLeft] = -100;
	motor[lift] = 100;
	motor[arm] = 15;
	wait1Msec(1000);
	}
	else {
	clearLCDLine(0);
	displayLCDCenteredString(0, "Default");
	motor[frontRight] = 110; // drive for 3.6 seconds
	motor[frontLeft] = 110;
	motor[backRight] = 110;
	motor[backLeft] = 110;
	wait1Msec(4000);
	motor[frontRight] = 0; // stop for 0.5 seconds
	motor[frontLeft] = 0;
	motor[backRight] = 0;
	motor[backLeft] = 0;
	motor[arm] = 127;
	wait1Msec(500);
	motor[lift] = 100; // lift for 1 seconds
	motor[arm] = 15;
	wait1Msec(2000);
	motor[lift] = 0; // back up for 1.6 seconds
	motor[backRight] = -110;
	motor[backLeft] = -110;
	motor[frontLeft] = -110;
	motor[frontRight] = -110;
	motor[arm] = 15;
	wait1Msec(4000);
	motor[frontRight] = -110; // turn for 1.5 seconds
	motor[frontLeft] = 110;
	motor[backRight] = -110;
	motor[backLeft] = 110;
	motor[arm] = 15;
	wait1Msec(1500);
	motor[lift] = -100; // lower lift for 1 second
	motor[arm] = 15;
	wait1Msec(1000);
	motor[frontRight] = 110;
	motor[frontLeft] = 110;
	motor[backRight] = 110;
	motor[backLeft] = 110;
	motor[arm] = 15;
	wait1Msec(500);
	motor[frontRight] = -100; // back up for 1 second
	motor[frontLeft] = -100;
	motor[backRight] = -100;
	motor[backLeft] = -100;
	motor[lift] = 100;
	motor[arm] = 15;
	wait1Msec(1000);
	}
	*/

 // motor[arm] = 10; // start arm and claw for .5 seconds
 // motor[claw] = 80;
//	wait1Msec(0);
//	motor[arm] = 20; //test to make speed is good
/*
	writeDebugStreamLine("Here");

	motor[claw] = 75;
	motor[frontRight] = 110; // drive for 4 seconds
	motor[frontLeft] = 110;
	motor[backRight] = 110;
	motor[backLeft] = 110;
	wait1Msec(4000);
	motor[frontRight] = 0; // stop for 0.5 seconds
	motor[frontLeft] = 0;
	motor[backRight] = 0;
	motor[backLeft] = 0;
	motor[arm] = 15;
	motor[claw] = 75;
	wait1Msec(500);
	motor[lift] = 100; // lift for 1.5 seconds
	motor[arm] = 15;
	wait1Msec(1500);
	motor[lift] = 0; // back up for 4 seconds
	motor[backRight] = -110;
	motor[backLeft] = -110;
	motor[frontLeft] = -110;
	motor[frontRight] = -110;
	motor[arm] = 15;
	motor[claw] = -75;
	wait1Msec(4000);
	motor[frontRight] = -110; // turn for 1.5 seconds
	motor[frontLeft] = 110;
	motor[backRight] = -110;
	motor[backLeft] = 110;
	motor[arm] = 15;
	wait1Msec(750);
	motor[lift] = -75; // lower lift for 1 second
	motor[arm] = 15;
	motor[claw] = 127;
	motor[pusher] = -15;
	wait1Msec(250);
	motor[frontRight] = 110; // turn for .5 seconds
	motor[frontLeft] = -110;
	motor[backRight] = 110;
	motor[backLeft] = -110;
	motor[arm] = 75;
	motor[pusher] = 15;
	wait1Msec(500);
	motor[frontRight] = -100; // back up for 1 second
	motor[frontLeft] = -100;
	motor[backRight] = -100;
	motor[backLeft] = -100;
	motor[arm] = 15;
	wait1Msec(1000);
	*/
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/


task usercontrol()
{
	writeDebugStreamLine("dab");

	while (true)
	{
		motor[frontRight] = vexRT[Ch3];
		motor[backLeft] = vexRT[Ch2];
		motor[backRight] = vexRT[Ch3];
		motor[frontLeft] = vexRT[Ch2];

		if(vexRT[Btn7D] == 1)
		{
			motor[lift] = 127;
		}
		else if(vexRT[Btn8D] == 1)
		{
			motor[lift] = -40;
		}
		else
		{
			motor[lift] = 0;
		}

		if(vexRT[Btn6U]==1)
		{
			motor[pusher] = -110;
		}
		else if(vexRT[Btn5U]==1)
		{
			motor[pusher] = 110;
		}
		else
		{
			motor[pusher]=0;
		}

		motor[arm] = vexRT[Ch3Xmtr2];
		motor[arm] = vexRT[Ch3Xmtr2];
		motor[claw] = vexRT[Ch2Xmtr2];
		motor[claw] = vexRT[Ch2Xmtr2];
		/* Possible Stall Code

		if(abs(vexRT(Ch3Xmtr2)) > 10)
		{
		motor[arm] = vexRT[Ch3Xmtr2];
		motor[arm] = vexRT[Ch3Xmtr2];

		}
		else
		{
		motor[arm] = 0;
		}
		if(abs(vexRT(Ch2Xmtr2)) > 10)
		{
		motor[claw] = vexRT[Ch2Xmtr2];
		motor[claw] = vexRT[Ch2Xmtr2];

		}
		else
		{
		motor[claw] = 0;
		}
		*/

	}

}
